In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'a':[10,20,30],'b':[20,30,40]})

In [3]:
df

a   b
0  10  20
1  20  30
2  30  40

In [ ]:
type(df['a'])

In [ ]:
df['a'].apply(lambda x: x**2)

In [ ]:
y = lambda x,e: x**e

In [ ]:
df['a'].apply(y, e=3)

In [4]:
def print_me(x):
    print(x)

In [5]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [6]:
df.apply(print_me, axis=1)

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [21]:
def avrg_3(x):
    return (x[0]+x[1]+x[2])/3

In [23]:
df.apply(avrg_3)

a    20.0
b    30.0
dtype: float64

In [24]:
def avrg_2(x):
    return (x[0]+x[1])/2

In [26]:
df.apply(avrg_2, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [27]:
import seaborn as sns

In [28]:
titanic = sns.load_dataset('titanic')

In [29]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [31]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [32]:
import numpy as np

In [33]:
def count_missing(vec):
    null_vec = pd.isnull(vec)
    null_count =  np.sum(null_vec)
    return null_count

In [34]:
def prop_missing(vec):
    num = count_missing(vec)
    dem = vec.size
    return num/ dem

In [35]:
def prop_complete(vec):
    return 1 - prop_missing(vec)

In [36]:
titanic.apply(count_missing)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [37]:
titanic.apply(prop_missing)

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [38]:
titanic.apply(prop_complete)

survived       1.000000
pclass         1.000000
sex            1.000000
age            0.801347
sibsp          1.000000
parch          1.000000
fare           1.000000
embarked       0.997755
class          1.000000
who            1.000000
adult_male     1.000000
deck           0.227834
embark_town    0.997755
alive          1.000000
alone          1.000000
dtype: float64

In [39]:
titanic.loc[pd.isnull(titanic.embark_town), :]

survived  pclass     sex   age  sibsp  parch  fare embarked  class  \
61          1       1  female  38.0      0      0  80.0      NaN  First   
829         1       1  female  62.0      0      0  80.0      NaN  First   

       who  adult_male deck embark_town alive  alone  
61   woman       False    B         NaN   yes   True  
829  woman       False    B         NaN   yes   True

In [41]:
cmis_row = titanic.apply(count_missing, axis=1)

In [42]:
cmis_row.value_counts()

1    549
0    182
2    160
dtype: int64

In [43]:
titanic['num_missing']= titanic.apply(count_missing, axis=1)

In [44]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  num_missing  
0    man        True  NaN  Southampton    no  False            1  
1  woman       False    C    Cherbourg   yes  False            0  
2  woman       False  NaN  Southampton   yes   True            1  
3  woman       False    C  Southampton   yes  False            0  
4    man        True  NaN  Southampton    no   True            1

In [45]:
titanic.loc[titanic.num_missing > 1,:].sample(10)

survived  pclass     sex  age  sibsp  parch      fare embarked  class  \
306         1       1  female  NaN      0      0  110.8833        C  First   
425         0       3    male  NaN      0      0    7.2500        S  Third   
459         0       3    male  NaN      0      0    7.7500        Q  Third   
718         0       3    male  NaN      0      0   15.5000        Q  Third   
388         0       3    male  NaN      0      0    7.7292        Q  Third   
330         1       3  female  NaN      2      0   23.2500        Q  Third   
837         0       3    male  NaN      0      0    8.0500        S  Third   
260         0       3    male  NaN      0      0    7.7500        Q  Third   
601         0       3    male  NaN      0      0    7.8958        S  Third   
507         1       1    male  NaN      0      0   26.5500        S  First   

       who  adult_male deck  embark_town alive  alone  num_missing  
306  woman       False  NaN    Cherbourg   yes   True            2  
425    man        True  NaN  Southampton    no   True            2  
459    man        True  NaN   Queenstown    no   True            2  
718    man        True  NaN   Queenstown    no   True            2  
388    man        True  NaN   Queenstown    no   True            2  
330  woman       False  NaN   Queenstown   yes  False            2  
837    man        True  NaN  Southampton    no   True            2  
260    man        True  NaN   Queenstown    no   True            2  
601    man        True  NaN  Southampton    no   True            2  
507    man        True  NaN  Southampton   yes   True            2

In [46]:
def avg_2(x,y):
    return (x+y)/2

In [47]:
avg_2(df['a'],df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [48]:
def avg_2_mod(x,y):
    if x == 20:
        return np.NAN
    else:
        return (x+y)/2

In [49]:
avg_2_mod(df['a'],df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [50]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [51]:
avg_2_mod_vec(df['a'],df['b'])

array([15., nan, 35.])

In [52]:
@np.vectorize
def v_avg_2_mod(x,y):
    if x == 20:
        return np.NAN
    else:
        return (x+y)/2

In [53]:
v_avg_2_mod(df['a'],df['b'])

array([15., nan, 35.])

In [55]:
import numba

In [56]:
@numba.vectorize
def v_avg_2_numba(x,y):
    if int(x) == 20:
        return np.NAN
    else:
        return (x+y)/2

In [58]:
v_avg_2_numba(df['a'].values,df['b'].values)

array([15., nan, 35.])